notifications:
  hipchat:
    rooms:
      secure: Pz5CQX/NtKLkk8c6kjhxipMS6kdQTj5jaeN9LC2k1IzERsqCYnx/nD2EV0cG4YJO0W3sMK3vaVgL5lLE3xHpe7wsLB/LWmxLY8QV0NJaSGOqqXAC4S5Yo7MRFd2S5fPWN7MC05SPpqiDveEle1fK6Gz7oHXSZxAFMyYnLRcaX3M=
language: php
php:
- '5.4'
- '5.5'
services:
- mysql
install:
- composer install --no-interaction
before_script:
- "./bin/tests install"
script:
- "./bin/tests run --no-install"
before_deploy:
- bin/release build-$TRAVIS_COMMIT
deploy:
  provider: s3
  access_key_id: AKIAIRCFCCGK6DG5STUA
  secret_access_key:
    secure: LZJrmQZzwxP3XTgiBULdtEnD86K+LAm8HgApnHMzEvrgZulm8UWwq5j+S5tIP1zZG5hUe+7AazcXT94/iPL4bI3cVbcrWyFOsLYunlzVXmKRHB+QWc66RfcaARi1anqzNB2fZti7FJ/TOIybvrInByvHeb1WKyvso9tsiqSqCO8=
  bucket: ushahidi-downloads
  local-dir: build
  upload-dir: V3/travis
  acl: public_read
  on:
    repo: ushahidi/platform
    all_branches: true
